KDIR	=	/root/IMX6Q/kernel_imx
SUBDIR  = 	/opt/poky/1.5.1/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/

all:
	$(SUBDIR)arm-poky-linux-gnueabi-gcc  -o testapp test.c 	

clean:
	rm testapp
